version: "3.7"

services:
  ase-server:
    image: blieusong/sybase-ase:latest
    hostname: ase-server
    working_dir: /home/sybase
    volumes:
      - sybase-data:/data
    ports:
      - 5000:5000
    tty: true
    entrypoint: "/home/sybase/bin/entrypoint.sh"

volumes:
  sybase-data: