version: "3.7"

services:
  ase-server:
    image: sybase/server:latest
    hostname: ase-server
    working_dir: /home/sybase
    volumes:
      - $HOME/sybase/data:/data
      - $HOME/sybase/ase:/home/sybase/ase
    networks:
      sybase-bridge:
        ipv4_address: 172.24.1.1

    tty: true
    entrypoint: "/home/sybase/bin/entrypoint.sh"

networks:
  sybase-bridge:
    external: 
      name: sybase-bridge
