version: "3.7"

services:
  ase-server:
    image: sybase/server:latest
    hostname: ase-server
    working_dir: /home/sybase
    volumes:
      - $HOME/sybase/data:/data
      - $HOME/sybase/ase:/home/sybase/ase
    networks:
      gbprod-bridge:

    tty: true
    entrypoint: "/home/sybase/bin/entrypoint.sh"

networks:
  gbprod-bridge:
    external: 
      name: gbprod-bridge
