#!/bin/sh
#
# SAP Adaptive Server Enterprise page size (KB):	4096
# Master device path:	/data/master.dat
# Error log path:	/opt/sap/ASE-16_0/install/DB_TEST.log
# Configuration file path:	/opt/sap/ASE-16_0/DB_TEST.cfg
# Directory for shared memory files:	/opt/sap/ASE-16_0
# License properties file:	/opt/sap/ASE-16_0/sysam/DB_TEST.properties
# Interfaces file directory:	/opt/sap
# SAP Adaptive Server Enterprise name:	DB_TEST
#
/opt/sap/ASE-16_0/bin/dataserver \
-d/data/master.dat \
-e/proc/1/fd/0 \
-c/opt/sap/ASE-16_0/DB_TEST.cfg \
-M/opt/sap/ASE-16_0 \
-N/opt/sap/ASE-16_0/sysam/DB_TEST.properties \
-i/opt/sap \
-sDB_TEST \

